name: Build-Windows-Zero-Fee-Static
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Загружаем XMRig встроенным методом GitHub
      - name: Checkout XMRig
        uses: actions/checkout@v4
        with:
          repository: xmrig/xmrig
          path: xmrig
          fetch-depth: 1

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make

      - name: Patch Donation
        shell: msys2 {0}
        run: |
          cd xmrig
          sed -i 's/kDefaultDonateLevel = 1/kDefaultDonateLevel = 0/g' src/donate.h
          sed -i 's/kMinimumDonateLevel = 1/kMinimumDonateLevel = 0/g' src/donate.h

      - name: Build Static EXE
        shell: msys2 {0}
        run: |
          cd xmrig
          mkdir build && cd build
          export PATH="/mingw64/bin:$PATH"
          cmake .. -G "MinGW Makefiles" \
                   -DXMRIG_DEPS=OFF \
                   -DWITH_HWLOC=OFF \
                   -DWITH_OPENSSL=OFF \
                   -DWITH_HTTP=OFF \
                   -DWITH_ADL=OFF \
                   -DWITH_NVML=OFF \
                   -DCMAKE_EXE_LINKER_FLAGS="-static"
          mingw32-make -j$(nproc)

      - name: Get Date
        id: date
        shell: bash
        run: echo "today=$(date +'%d.%m.%Y')" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: XMRig (${{ steps.date.outputs.today }}) no donate
          path: xmrig/build/xmrig.exe
