name: Build-Windows-Zero-Fee-Static

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      actions: write
    steps:
      - name: Get Latest Release Info
        id: xmrig_info
        uses: pozetiv/github-action-get-latest-release@v0.7.0
        with:
          repository: xmrig/xmrig
          excludes: prerelease, draft

      - name: Checkout XMRig
        uses: actions/checkout@v4
        with:
          repository: xmrig/xmrig
          ref: ${{ steps.xmrig_info.outputs.release }}
          path: xmrig

      - name: Setup Info and Rename
        shell: bash
        run: |
          # Форматируем дату из ISO (2024-05-15T...) в DD.MM.YYYY
          RAW_DATE="${{ steps.xmrig_info.outputs.published_at }}"
          FORM_DATE=$(date -d "$RAW_DATE" +"%d.%m.%Y")
          FULL_NAME="XMRig ${{ steps.xmrig_info.outputs.release }} ($FORM_DATE) no donate"
          
          echo "FINAL_NAME=$FULL_NAME" >> $GITHUB_ENV
          
          # Переименовываем запуск в списке Actions через API
          curl -L -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            "https://api.github.com{{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -d "{\"display_title\":\"$FULL_NAME\"}"

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make

      - name: Patch and Build
        shell: msys2 {0}
        run: |
          cd xmrig
          # Патчим комиссию
          sed -i 's/kDefaultDonateLevel = 1/kDefaultDonateLevel = 0/g' src/donate.h
          sed -i 's/kMinimumDonateLevel = 1/kMinimumDonateLevel = 0/g' src/donate.h
          
          # Собираем
          mkdir -p build && cd build
          export PATH="/mingw64/bin:$PATH"
          cmake .. -G "MinGW Makefiles" -DXMRIG_DEPS=OFF -DWITH_HWLOC=OFF -DWITH_OPENSSL=OFF -DWITH_HTTP=OFF -DWITH_ADL=OFF -DWITH_NVML=OFF -DCMAKE_EXE_LINKER_FLAGS="-static"
          mingw32-make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FINAL_NAME }}
          path: xmrig/build/xmrig.exe
